src/Entity/Presence.php
<?php

namespace App\Entity;

use App\Repository\PresenceRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PresenceRepository::class)]
class Presence
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $date_day = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTime $arrival_hour = null;

    #[ORM\Column(type: Types::TIME_MUTABLE)]
    private ?\DateTime $departure_time = null;

    #[ORM\ManyToOne(inversedBy: 'presences')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Child $child = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateDay(): ?\DateTimeImmutable
    {
        return $this->date_day;
    }

    public function setDateDay(\DateTimeImmutable $date_day): static
    {
        $this->date_day = $date_day;

        return $this;
    }

    public function getArrivalHour(): ?\DateTime
    {
        return $this->arrival_hour;
    }

    public function setArrivalHour(\DateTime $arrival_hour): static
    {
        $this->arrival_hour = $arrival_hour;

        return $this;
    }

    public function getDepartureTime(): ?\DateTime
    {
        return $this->departure_time;
    }

    public function setDepartureTime(\DateTime $departure_time): static
    {
        $this->departure_time = $departure_time;

        return $this;
    }

    public function getChild(): ?Child
    {
        return $this->child;
    }

    public function setChild(?Child $child): static
    {
        $this->child = $child;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 50)]
    private ?string $name = null;

    #[ORM\Column(length: 50)]
    private ?string $first_name = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $birthday = null;

    #[ORM\Column(length: 150)]
    private ?string $adress = null;

    #[ORM\Column(length: 100)]
    private ?string $phone = null;

    /**
     * @var Collection<int, Activities>
     */
    #[ORM\OneToMany(targetEntity: Activities::class, mappedBy: 'user')]
    private Collection $activities;

    /**
     * @var Collection<int, Child>
     */
    #[ORM\ManyToMany(targetEntity: Child::class, inversedBy: 'users')]
    private Collection $child;

    #[ORM\Column(type: 'boolean')]
    private bool $isVerified = false;

    public function __construct()
    {
        $this->activities = new ArrayCollection();
        $this->child = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    #[\Deprecated]
    public function eraseCredentials(): void
    {
        // @deprecated, to be removed when upgrading to Symfony 8
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): static
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getBirthday(): ?\DateTimeImmutable
    {
        return $this->birthday;
    }

    public function setBirthday(\DateTimeImmutable $birthday): static
    {
        $this->birthday = $birthday;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): static
    {
        $this->adress = $adress;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): static
    {
        $this->phone = $phone;

        return $this;
    }

    /**
     * @return Collection<int, Activities>
     */
    public function getActivities(): Collection
    {
        return $this->activities;
    }

    public function addActivity(Activities $activity): static
    {
        if (!$this->activities->contains($activity)) {
            $this->activities->add($activity);
            $activity->setUser($this);
        }

        return $this;
    }

    public function removeActivity(Activities $activity): static
    {
        if ($this->activities->removeElement($activity)) {
            // set the owning side to null (unless already changed)
            if ($activity->getUser() === $this) {
                $activity->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Child>
     */
    public function getChild(): Collection
    {
        return $this->child;
    }

    public function addChild(Child $child): static
    {
        if (!$this->child->contains($child)) {
            $this->child->add($child);
        }

        return $this;
    }

    public function removeChild(Child $child): static
    {
        $this->child->removeElement($child);

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;
        return $this;
    }
}

src/Form/PresenceType.php
<?php

namespace App\Form;

use App\Entity\Presence;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\TimeType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PresenceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date_day', DateType::class, [
                'widget' => 'single_text',
                'label' => 'Date',
            ])
            ->add('arrival_hour', TimeType::class, [
                'label' => 'Heure d\'arrivée',
            ])
            ->add('departure_time', TimeType::class, [
                'label' => 'Heure de départ',
            ])
            // Unmapped text input used by Stimulus autocomplete
            ->add('child_search', TextType::class, [
                'mapped' => false,
                'required' => false,
                'label' => 'Enfant',
                'attr' => [
                    'placeholder' => 'Rechercher un enfant...',
                    'data-controller' => 'autocomplete',
                    'data-action' => 'input->autocomplete#search',
                    'data-autocomplete-target' => 'input',
                    // configure controller for children search
                    'data-autocomplete-search-url' => '/child/child-search',
                    // hidden input that will be posted
                    'data-autocomplete-hidden-name' => 'child_id',
                    // single selection
                    'data-autocomplete-multiple' => '0',
                    // initial value when editing
                    'data-autocomplete-initial-id' => $builder->getData() && $builder->getData()->getChild() ? $builder->getData()->getChild()->getId() : '',
                    'data-autocomplete-initial-text' => $builder->getData() && $builder->getData()->getChild() ? trim(($builder->getData()->getChild()->getFirstName() ?? '') . ' ' . ($builder->getData()->getChild()->getName() ?? '')) : '',
                ],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Presence::class,
        ]);
    }
}

src/Controller/PresenceController.php
<?php

namespace App\Controller;

use App\Entity\Presence;
use App\Form\PresenceType;
use App\Repository\PresenceRepository;
use App\Repository\ChildRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/presence')]
final class PresenceController extends AbstractController
{
    #[Route(name: 'app_presence_index', methods: ['GET'])]
    public function index(PresenceRepository $presenceRepository): Response
    {
        return $this->render('presence/index.html.twig', [
            'presences' => $presenceRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_presence_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, ChildRepository $childRepository): Response
    {
        $presence = new Presence();
        $form = $this->createForm(PresenceType::class, $presence);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // Map submitted child_id (from hidden input) to the entity
            $childId = $request->request->get('child_id');
            if ($childId) {
                $child = $childRepository->find($childId);
                if ($child) {
                    $presence->setChild($child);
                }
            }
            $entityManager->persist($presence);
            $entityManager->flush();

            return $this->redirectToRoute('app_presence_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('presence/new.html.twig', [
            'presence' => $presence,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_presence_show', methods: ['GET'])]
    public function show(?Presence $presence): Response
    {
        return $this->render('presence/show.html.twig', [
            'presence' => $presence,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_presence_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Presence $presence, EntityManagerInterface $entityManager, ChildRepository $childRepository): Response
    {
        $form = $this->createForm(PresenceType::class, $presence);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $childId = $request->request->get('child_id');
            if ($childId) {
                $child = $childRepository->find($childId);
                if ($child) {
                    $presence->setChild($child);
                }
            }
            $entityManager->flush();

            return $this->redirectToRoute('app_presence_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('presence/edit.html.twig', [
            'presence' => $presence,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_presence_delete', methods: ['POST'])]
    public function delete(Request $request, Presence $presence, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$presence->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($presence);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_presence_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/presence/_delete_form.html.twig
<form method="post" action="{{ path('app_presence_delete', {'id': presence.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer cette présence?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ presence.id) }}">
    <button class="btn">Supprimer</button>
</form>

templates/presence/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/presence/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier présence{% endblock %}

{% block body %}
    <h1>Modifier présence</h1>

    {{ include('presence/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_presence_index') }}">Retour à la liste</a>

    {{ include('presence/_delete_form.html.twig') }}
{% endblock %}

templates/presence/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des présences{% endblock %}

{% block body %}
    <h1>Liste des présences</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Date</th>
                <th>Enfant</th>
                <th>Heure d'arrivée</th>
                <th>Heure de départ</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for presence in presences %}
            <tr>
                <td>{{ presence.dateDay ? presence.dateDay|date('d/m/Y') : '' }}</td>
                <td>{{ presence.child.name }} {{ presence.child.firstName }}</td>
                <td>{{ presence.arrivalHour ? presence.arrivalHour|date('H:i:s') : '' }}</td>
                <td>{{ presence.departureTime ? presence.departureTime|date('H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_presence_show', {'id': presence.id}) }}">Voir</a>
                    <a href="{{ path('app_presence_edit', {'id': presence.id}) }}">Modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">Aucune présence trouvée</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_presence_new') }}">Nouvelle présence</a>
{% endblock %}

templates/presence/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle présence{% endblock %}

{% block body %}
    <h1>Nouvelle présence</h1>

    {{ include('presence/_form.html.twig') }}

    <a href="{{ path('app_presence_index') }}">Retour à la liste</a>
{% endblock %}

templates/presence/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Présence{% endblock %}

{% block body %}
    <h1>Présence</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Date</th>
                <td>{{ presence.dateDay ? presence.dateDay|date('d/m/Y') : '' }}</td>
            </tr>
            <tr>
                <th>Heure d'arrivée</th>
                <td>{{ presence.arrivalHour ? presence.arrivalHour|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Heure de départ</th>
                <td>{{ presence.departureTime ? presence.departureTime|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Enfant</th>
                <td>{{ presence.child.name }} {{ presence.child.firstName }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_presence_index') }}">Retour à la liste</a>

    <a href="{{ path('app_presence_edit', {'id': presence.id}) }}">Modifier</a>

    {{ include('presence/_delete_form.html.twig') }}
{% endblock %}